### PR TITLE
issue52-single-star-view-Fatemeh

### PR DESCRIPTION
**Pull request by FatemRahimi**
## Naming Rules

Name your PR like this: ISSUENUMBER-TITLE-YOURNAME

## Description:
After clicking on the STAR's name in Dashboard it  redirect to page with star name

Write a summary of your change. Explain why you have made it.

## Related to

Make sure you include the issue number with a hash sign # so Github can link this PR to the right issue, like this:

Fixes #1

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

### CODE REVIEW

**Comment by FatemRahimi** [comment]
removed conflicts.

**Comment by Mesgna616** [comment]
Hi Fatemeh , i think what we are trying to accomplish is when the name of star is clicked to take us to a new page showing us only one star with the id as its paramater. I think you have started good by including the link on the star name as per requriment , however you have directed it to dashboard , which we might need create a separate route to be rendered on single page. For further information could you please refer the issue to Mark .

**Comment by FatemRahimi** [comment]
Thank you for your email. Yes I will do it.

**Comment by FatemRahimi** [comment]
> Hi Fatemeh , i think what we are trying to accomplish is when the name of star is clicked to take us to a new page showing us only one star with the id as its paramater. I think you have started good by including the link on the star name as per requriment , however you have directed it to dashboard , which we might need create a separate route to be rendered on single page. For further information could you please refer the issue to Mark .

Hey Mesgna, thank you for your suggestion. but I need to get more, which page do you mean?

**Comment by FatemRahimi** [comment]
> Hi Fatemeh , i think what we are trying to accomplish is when the name of star is clicked to take us to a new page showing us only one star with the id as its paramater. I think you have started good by including the link on the star name as per requriment , however you have directed it to dashboard , which we might need create a separate route to be rendered on single page. For further information could you please refer the issue to Mark .

Hey Mesgna, thank you for the review . I am waiting to get advice from Mark.Please wait?

**Pull request closed without merging**
